# Generated by Django 5.2.5 on 2025-10-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usu', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_evento', models.CharField(max_length=50, unique=True)),
                ('nombre_del_evento', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.organizador')),
            ],
        ),
    ]
